<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateMunicipiosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('municipios', function (Blueprint $table) {
            $table->id('id_municipio');
            $table->string('nombre', 100);
            $table->foreignId('id_departamento')->references('id_departamento')->on('departamentos')->onUpdate('cascade');
            // $table->timestamps();
        });

        DB::table('municipios')->insert([

            //amazonas
            ['nombre' => 'El Encanto', 'id_departamento' => 1],
            ['nombre' => 'La Chorrera', 'id_departamento' => 1],
            ['nombre' => 'La Pedrera', 'id_departamento' => 1],
            ['nombre' => 'La Victoria', 'id_departamento' => 1],
            ['nombre' => 'Leticia (Capital)', 'id_departamento' => 1],
            ['nombre' => 'Mirití Paraná', 'id_departamento' => 1],
            ['nombre' => 'Puerto Alegría', 'id_departamento' => 1],
            ['nombre' => 'Puerto Arica', 'id_departamento' => 1],
            ['nombre' => 'Puerto Nariño', 'id_departamento' => 1],
            ['nombre' => 'Puerto Santander', 'id_departamento' => 1],
            ['nombre' => 'Tarapacá', 'id_departamento' => 1],

            //antioquia
            ['nombre' => 'Cáceres', 'id_departamento' => 2],
            ['nombre' => 'Caucasia', 'id_departamento' => 2],
            ['nombre' => 'El bagre', 'id_departamento' => 2],
            ['nombre' => 'Nechí', 'id_departamento' => 2],
            ['nombre' => 'Tarazá', 'id_departamento' => 2],
            ['nombre' => 'Zaragoza', 'id_departamento' => 2],
            ['nombre' => 'Caracolí', 'id_departamento' => 2],
            ['nombre' => 'Maceo', 'id_departamento' => 2],
            ['nombre' => 'Puerto Berrio', 'id_departamento' => 2],
            ['nombre' => 'Puerto Nare', 'id_departamento' => 2],
            ['nombre' => 'Puerto Triunfo', 'id_departamento' => 2],
            ['nombre' => 'Yondó', 'id_departamento' => 2],    
            ['nombre' => 'Amalfi', 'id_departamento' => 2],    
            ['nombre' => 'Anorí', 'id_departamento' => 2],    
            ['nombre' => 'Cisneros', 'id_departamento' => 2],    
            ['nombre' => 'Remedios', 'id_departamento' => 2],    
            ['nombre' => 'San Roque', 'id_departamento' => 2],    
            ['nombre' => 'Santo Domingo', 'id_departamento' => 2],    
            ['nombre' => 'Segovia', 'id_departamento' => 2],    
            ['nombre' => 'Vegachí', 'id_departamento' => 2],    
            ['nombre' => 'Yalí', 'id_departamento' => 2],    
            ['nombre' => 'Yolombó', 'id_departamento' => 2],    
            ['nombre' => 'Angostura', 'id_departamento' => 2],    
            ['nombre' => 'Belmira', 'id_departamento' => 2],    
            ['nombre' => 'Briceño', 'id_departamento' => 2],    
            ['nombre' => 'Campamento', 'id_departamento' => 2],    
            ['nombre' => 'Carolina del Príncipe', 'id_departamento' => 2],    
            ['nombre' => 'Donmatías', 'id_departamento' => 2],    
            ['nombre' => 'Entrerríos', 'id_departamento' => 2],    
            ['nombre' => 'Gómez Plata', 'id_departamento' => 2],
            ['nombre' => 'Guadalupe', 'id_departamento' => 2],
            ['nombre' => 'Ituango', 'id_departamento' => 2],
            ['nombre' => 'San Andrés de Cuerquia', 'id_departamento' => 2],
            ['nombre' => 'San José de la Montaña', 'id_departamento' => 2],
            ['nombre' => 'San Pedro de los Milagros', 'id_departamento' => 2],
            ['nombre' => 'Santa Rosa de Osos', 'id_departamento' => 2],
            ['nombre' => 'Toledo', 'id_departamento' => 2],
            ['nombre' => 'Valdivia', 'id_departamento' => 2],
            ['nombre' => 'Yarumal', 'id_departamento' => 2],
            ['nombre' => 'Abriaquí', 'id_departamento' => 2],
            ['nombre' => 'Antioquia', 'id_departamento' => 2],
            ['nombre' => 'Anzá', 'id_departamento' => 2],
            ['nombre' => 'Armenia', 'id_departamento' => 2],
            ['nombre' => 'Buriticá', 'id_departamento' => 2],
            ['nombre' => 'Caicedo', 'id_departamento' => 2],
            ['nombre' => 'Cañasgordas', 'id_departamento' => 2],
            ['nombre' => 'Dabeiba', 'id_departamento' => 2],
            ['nombre' => 'Ebéjico', 'id_departamento' => 2],
            ['nombre' => 'Frontino', 'id_departamento' => 2],
            ['nombre' => 'Giraldo', 'id_departamento' => 2],
            ['nombre' => 'Heliconia', 'id_departamento' => 2],
            ['nombre' => 'Liborina', 'id_departamento' => 2],
            ['nombre' => 'Olaya', 'id_departamento' => 2],
            ['nombre' => 'Peque', 'id_departamento' => 2],
            ['nombre' => 'Sabanalarga', 'id_departamento' => 2],
            ['nombre' => 'San Jerónimo', 'id_departamento' => 2],
            ['nombre' => 'Sopetrán', 'id_departamento' => 2],
            ['nombre' => 'Uramita', 'id_departamento' => 2],
            ['nombre' => 'Abejorral', 'id_departamento' => 2],
            ['nombre' => 'Alejandría', 'id_departamento' => 2],
            ['nombre' => 'Argelia', 'id_departamento' => 2],
            ['nombre' => 'Carmen de Viboral', 'id_departamento' => 2],
            ['nombre' => 'Cocorná', 'id_departamento' => 2],
            ['nombre' => 'Concepción', 'id_departamento' => 2],
            ['nombre' => 'El Peñol', 'id_departamento' => 2],
            ['nombre' => 'El Retiro', 'id_departamento' => 2],
            ['nombre' => 'El Santuario', 'id_departamento' => 2],
            ['nombre' => 'Granada', 'id_departamento' => 2],
            ['nombre' => 'Guarne', 'id_departamento' => 2],
            ['nombre' => 'Guatapé', 'id_departamento' => 2],
            ['nombre' => 'La Ceja', 'id_departamento' => 2],
            ['nombre' => 'La Unión', 'id_departamento' => 2],
            ['nombre' => 'Marinilla', 'id_departamento' => 2],
            ['nombre' => 'Nariño', 'id_departamento' => 2],
            ['nombre' => 'Rionegro', 'id_departamento' => 2],
            ['nombre' => 'San Carlos', 'id_departamento' => 2],
            ['nombre' => 'San Francisco', 'id_departamento' => 2],
            ['nombre' => 'San Luis', 'id_departamento' => 2],
            ['nombre' => 'San Rafael', 'id_departamento' => 2],
            ['nombre' => 'San Vicente', 'id_departamento' => 2],
            ['nombre' => 'Sonsón', 'id_departamento' => 2],
            ['nombre' => 'Amagá', 'id_departamento' => 2],
            ['nombre' => 'Andes', 'id_departamento' => 2],
            ['nombre' => 'Angelópolis', 'id_departamento' => 2],
            ['nombre' => 'Betania', 'id_departamento' => 2],
            ['nombre' => 'Betulia', 'id_departamento' => 2],
            ['nombre' => 'Caramanta', 'id_departamento' => 2],
            ['nombre' => 'Ciudad Bolívar', 'id_departamento' => 2],
            ['nombre' => 'Concordia', 'id_departamento' => 2],
            ['nombre' => 'Fredonia', 'id_departamento' => 2],
            ['nombre' => 'Hispania', 'id_departamento' => 2],
            ['nombre' => 'Jardín', 'id_departamento' => 2],
            ['nombre' => 'Jericó', 'id_departamento' => 2],
            ['nombre' => 'La Pintada', 'id_departamento' => 2],
            ['nombre' => 'Montebello', 'id_departamento' => 2],
            ['nombre' => 'Pueblorrico', 'id_departamento' => 2],
            ['nombre' => 'Salgar', 'id_departamento' => 2],
            ['nombre' => 'Santa Bárbara', 'id_departamento' => 2],
            ['nombre' => 'Támesis', 'id_departamento' => 2],
            ['nombre' => 'Tarso', 'id_departamento' => 2],
            ['nombre' => 'Titiribí', 'id_departamento' => 2],
            ['nombre' => 'Urrao', 'id_departamento' => 2],
            ['nombre' => 'Valparaíso', 'id_departamento' => 2],
            ['nombre' => 'Venecia', 'id_departamento' => 2],
            ['nombre' => 'Apartadó', 'id_departamento' => 2],
            ['nombre' => 'Arboletes', 'id_departamento' => 2],
            ['nombre' => 'Carepa', 'id_departamento' => 2],
            ['nombre' => 'Chigorodó', 'id_departamento' => 2],
            ['nombre' => 'Murindó', 'id_departamento' => 2],
            ['nombre' => 'Mutatá', 'id_departamento' => 2],
            ['nombre' => 'Necoclí', 'id_departamento' => 2],
            ['nombre' => 'San Juan de Urabá', 'id_departamento' => 2],
            ['nombre' => 'San Pedro de Urabá', 'id_departamento' => 2],
            ['nombre' => 'Turbo', 'id_departamento' => 2],
            ['nombre' => 'Vigía del Fuerte', 'id_departamento' => 2],
            ['nombre' => 'Barbosa', 'id_departamento' => 2],
            ['nombre' => 'Bello', 'id_departamento' => 2],
            ['nombre' => 'Caldas', 'id_departamento' => 2],
            ['nombre' => 'Copacabana', 'id_departamento' => 2],
            ['nombre' => 'Envigado', 'id_departamento' => 2],
            ['nombre' => 'Girardota', 'id_departamento' => 2],
            ['nombre' => 'Itagüí', 'id_departamento' => 2],
            ['nombre' => 'La Estrella', 'id_departamento' => 2],
            ['nombre' => 'Medellín (Capital)', 'id_departamento' => 2],
            ['nombre' => 'Sabaneta', 'id_departamento' => 2],

            //arauca
            ['nombre' => 'Arauca (Capital)', 'id_departamento' => 3],
            ['nombre' => 'Arauquita', 'id_departamento' => 3],
            ['nombre' => 'Cravo Norte', 'id_departamento' => 3],
            ['nombre' => 'Fortul', 'id_departamento' => 3],
            ['nombre' => 'Puerto Rondón', 'id_departamento' => 3],
            ['nombre' => 'Saravena', 'id_departamento' => 3],
            ['nombre' => 'Tame', 'id_departamento' => 3],

            //atlántico
            ['nombre' => 'Barranquilla (Capital)', 'id_departamento' => 4],
            ['nombre' => 'Galapa', 'id_departamento' => 4],
            ['nombre' => 'Malambo', 'id_departamento' => 4],
            ['nombre' => 'Puerto Colombia', 'id_departamento' => 4],
            ['nombre' => 'Soledad', 'id_departamento' => 4],
            ['nombre' => 'Baranoa', 'id_departamento' => 4],
            ['nombre' => 'Palmar de Valera', 'id_departamento' => 4],
            ['nombre' => 'Polonuevo', 'id_departamento' => 4],
            ['nombre' => 'Ponedera', 'id_departamento' => 4],
            ['nombre' => 'Sabanagrande', 'id_departamento' => 4],
            ['nombre' => 'Sabanalarga', 'id_departamento' => 4],
            ['nombre' => 'Santo Tomás', 'id_departamento' => 4],
            ['nombre' => 'Juan de Acosta', 'id_departamento' => 4],
            ['nombre' => 'Piojó', 'id_departamento' => 4],
            ['nombre' => 'Tubará', 'id_departamento' => 4],
            ['nombre' => 'Usiacurí', 'id_departamento' => 4],
            ['nombre' => 'Campo de la cruz', 'id_departamento' => 4],
            ['nombre' => 'Candelaria', 'id_departamento' => 4],
            ['nombre' => 'Luruaco', 'id_departamento' => 4],
            ['nombre' => 'Manatí', 'id_departamento' => 4],
            ['nombre' => 'Repelón', 'id_departamento' => 4],
            ['nombre' => 'Santa Lucía', 'id_departamento' => 4],
            ['nombre' => 'Suán', 'id_departamento' => 4],

            //bolívar
            ['nombre' => 'Achí', 'id_departamento' => 5],
            ['nombre' => 'Altos del Rosario', 'id_departamento' => 5],
            ['nombre' => 'Arenal', 'id_departamento' => 5],
            ['nombre' => 'Arjona', 'id_departamento' => 5],
            ['nombre' => 'Arroyohondo', 'id_departamento' => 5],
            ['nombre' => 'Barranco de Loba', 'id_departamento' => 5],
            ['nombre' => 'Calamar', 'id_departamento' => 5],
            ['nombre' => 'Cantagallo', 'id_departamento' => 5],
            ['nombre' => 'Cartagena (Capital)', 'id_departamento' => 5],
            ['nombre' => 'Cicuco', 'id_departamento' => 5],
            ['nombre' => 'Clemencia', 'id_departamento' => 5],
            ['nombre' => 'Córdoba', 'id_departamento' => 5],
            ['nombre' => 'El Carmen de Bolívar', 'id_departamento' => 5],
            ['nombre' => 'El Guamo', 'id_departamento' => 5],
            ['nombre' => 'El Peñón', 'id_departamento' => 5],
            ['nombre' => 'Hatillo de Loba', 'id_departamento' => 5],
            ['nombre' => 'Magangué', 'id_departamento' => 5],
            ['nombre' => 'Mahates', 'id_departamento' => 5],
            ['nombre' => 'Margarita', 'id_departamento' => 5],
            ['nombre' => 'María la Baja', 'id_departamento' => 5],
            ['nombre' => 'Mompós', 'id_departamento' => 5],
            ['nombre' => 'Montecristo', 'id_departamento' => 5],
            ['nombre' => 'Morales', 'id_departamento' => 5],
            ['nombre' => 'Norosí', 'id_departamento' => 5],
            ['nombre' => 'Pinillos', 'id_departamento' => 5],
            ['nombre' => 'Regidor', 'id_departamento' => 5],
            ['nombre' => 'Río Viejo', 'id_departamento' => 5],
            ['nombre' => 'San Cristóbal', 'id_departamento' => 5],
            ['nombre' => 'San Estanislao', 'id_departamento' => 5],
            ['nombre' => 'San Fernando', 'id_departamento' => 5],
            ['nombre' => 'San Jacinto', 'id_departamento' => 5],
            ['nombre' => 'San Jacinto del Cauca', 'id_departamento' => 5],
            ['nombre' => 'San Juan Nepomuceno', 'id_departamento' => 5],
            ['nombre' => 'San Martín de Loba', 'id_departamento' => 5],
            ['nombre' => 'San Pablo de Borbur', 'id_departamento' => 5],
            ['nombre' => 'Santa Catalina', 'id_departamento' => 5],
            ['nombre' => 'Santa Rosa', 'id_departamento' => 5],
            ['nombre' => 'Santa Rosa del Sur', 'id_departamento' => 5],
            ['nombre' => 'Simití', 'id_departamento' => 5],
            ['nombre' => 'Soplaviento', 'id_departamento' => 5],
            ['nombre' => 'Talaigua Nuevo', 'id_departamento' => 5],
            ['nombre' => 'Tiquisio', 'id_departamento' => 5],
            ['nombre' => 'Turbaco', 'id_departamento' => 5],
            ['nombre' => 'Turbaná', 'id_departamento' => 5],
            ['nombre' => 'Villanueva', 'id_departamento' => 5],
            ['nombre' => 'Zambrano', 'id_departamento' => 5],

            //boyacá
            ['nombre' => 'Almeida', 'id_departamento' => 6],
            ['nombre' => 'Aquitania', 'id_departamento' => 6],
            ['nombre' => 'Arcabuco', 'id_departamento' => 6],
            ['nombre' => 'Belén', 'id_departamento' => 6],
            ['nombre' => 'Berbeo', 'id_departamento' => 6],
            ['nombre' => 'Betéitiva', 'id_departamento' => 6],
            ['nombre' => 'Boavita', 'id_departamento' => 6],
            ['nombre' => 'Boyacá', 'id_departamento' => 6],
            ['nombre' => 'Briceño', 'id_departamento' => 6],
            ['nombre' => 'Buena Vista', 'id_departamento' => 6],
            ['nombre' => 'Busbanzá', 'id_departamento' => 6],
            ['nombre' => 'Caldas', 'id_departamento' => 6],
            ['nombre' => 'Campohermoso', 'id_departamento' => 6],
            ['nombre' => 'Cerinza', 'id_departamento' => 6],
            ['nombre' => 'Chinavita', 'id_departamento' => 6],
            ['nombre' => 'Chiquinquirá', 'id_departamento' => 6],
            ['nombre' => 'Chíquiza', 'id_departamento' => 6],
            ['nombre' => 'Chiscas', 'id_departamento' => 6],
            ['nombre' => 'Chita', 'id_departamento' => 6],
            ['nombre' => 'Chitaraque', 'id_departamento' => 6],
            ['nombre' => 'Chivatá', 'id_departamento' => 6],
            ['nombre' => 'Chivor', 'id_departamento' => 6],
            ['nombre' => 'Ciénega', 'id_departamento' => 6],
            ['nombre' => 'Cómbita', 'id_departamento' => 6],
            ['nombre' => 'Coper', 'id_departamento' => 6],
            ['nombre' => 'Corrales', 'id_departamento' => 6],
            ['nombre' => 'Covarachía', 'id_departamento' => 6],
            ['nombre' => 'Cubará', 'id_departamento' => 6],
            ['nombre' => 'Cucaita', 'id_departamento' => 6],
            ['nombre' => 'Cuítiva', 'id_departamento' => 6],
            ['nombre' => 'Duitama', 'id_departamento' => 6],
            ['nombre' => 'El Cocuy', 'id_departamento' => 6],
            ['nombre' => 'El Espino', 'id_departamento' => 6],
            ['nombre' => 'Firavitoba', 'id_departamento' => 6],
            ['nombre' => 'Floresta', 'id_departamento' => 6],
            ['nombre' => 'Gachantivá', 'id_departamento' => 6],
            ['nombre' => 'Gameza', 'id_departamento' => 6],
            ['nombre' => 'Garagoa', 'id_departamento' => 6],
            ['nombre' => 'Guacamayas', 'id_departamento' => 6],
            ['nombre' => 'Guateque', 'id_departamento' => 6],
            ['nombre' => 'Guayatá', 'id_departamento' => 6],
            ['nombre' => 'Güicán', 'id_departamento' => 6],
            ['nombre' => 'Iza', 'id_departamento' => 6],
            ['nombre' => 'Jenesano', 'id_departamento' => 6],
            ['nombre' => 'Jericó', 'id_departamento' => 6],
            ['nombre' => 'La Capilla', 'id_departamento' => 6],
            ['nombre' => 'La Uvita', 'id_departamento' => 6],
            ['nombre' => 'La Victoria', 'id_departamento' => 6],
            ['nombre' => 'Labranzagrande', 'id_departamento' => 6],
            ['nombre' => 'Macanal', 'id_departamento' => 6],
            ['nombre' => 'Maripí', 'id_departamento' => 6],
            ['nombre' => 'Miraflores', 'id_departamento' => 6],
            ['nombre' => 'Mongua', 'id_departamento' => 6],
            ['nombre' => 'Monguí', 'id_departamento' => 6],
            ['nombre' => 'Moniquirá', 'id_departamento' => 6],
            ['nombre' => 'Motavita', 'id_departamento' => 6],
            ['nombre' => 'Muzo', 'id_departamento' => 6],
            ['nombre' => 'Nobsa', 'id_departamento' => 6],
            ['nombre' => 'Nuevo Colón', 'id_departamento' => 6],
            ['nombre' => 'Oicatá', 'id_departamento' => 6],
            ['nombre' => 'Otanche', 'id_departamento' => 6],
            ['nombre' => 'Pachavita', 'id_departamento' => 6],
            ['nombre' => 'Páez', 'id_departamento' => 6],
            ['nombre' => 'Paipa', 'id_departamento' => 6],
            ['nombre' => 'Pajarito', 'id_departamento' => 6],
            ['nombre' => 'Panqueba', 'id_departamento' => 6],
            ['nombre' => 'Pauna', 'id_departamento' => 6],
            ['nombre' => 'Paya', 'id_departamento' => 6],
            ['nombre' => 'Paz de Río', 'id_departamento' => 6],
            ['nombre' => 'Pesca', 'id_departamento' => 6],
            ['nombre' => 'Pisba', 'id_departamento' => 6],
            ['nombre' => 'Puerto Puerto Boyacá', 'id_departamento' => 6],
            ['nombre' => 'Quípama', 'id_departamento' => 6],
            ['nombre' => 'Ramiriquí', 'id_departamento' => 6],
            ['nombre' => 'Ráquira', 'id_departamento' => 6],
            ['nombre' => 'Rondón', 'id_departamento' => 6],
            ['nombre' => 'Saboyá', 'id_departamento' => 6],
            ['nombre' => 'Sáchica', 'id_departamento' => 6],
            ['nombre' => 'Samacá', 'id_departamento' => 6],
            ['nombre' => 'San Eduardo', 'id_departamento' => 6],
            ['nombre' => 'San José de Pare', 'id_departamento' => 6],
            ['nombre' => 'San Luis de Gaceno', 'id_departamento' => 6],
            ['nombre' => 'San Mateo', 'id_departamento' => 6],
            ['nombre' => 'San Miguel de Sema', 'id_departamento' => 6],
            ['nombre' => 'San Pablo de Borbur', 'id_departamento' => 6],
            ['nombre' => 'Santa María', 'id_departamento' => 6],
            ['nombre' => 'Santa Rosa de Viterbo', 'id_departamento' => 6],
            ['nombre' => 'Santa Sofía', 'id_departamento' => 6],
            ['nombre' => 'Santana', 'id_departamento' => 6],
            ['nombre' => 'Sativanorte', 'id_departamento' => 6],
            ['nombre' => 'Sativasur', 'id_departamento' => 6],
            ['nombre' => 'Siachoque', 'id_departamento' => 6],
            ['nombre' => 'Soatá', 'id_departamento' => 6],
            ['nombre' => 'Socha', 'id_departamento' => 6],
            ['nombre' => 'Socotá', 'id_departamento' => 6],
            ['nombre' => 'Sogamoso', 'id_departamento' => 6],
            ['nombre' => 'Somondoco', 'id_departamento' => 6],
            ['nombre' => 'Sora', 'id_departamento' => 6],
            ['nombre' => 'Soracá', 'id_departamento' => 6],
            ['nombre' => 'Sotaquirá', 'id_departamento' => 6],
            ['nombre' => 'Susacón', 'id_departamento' => 6],
            ['nombre' => 'Sutamarchán', 'id_departamento' => 6],
            ['nombre' => 'Sutatenza', 'id_departamento' => 6],
            ['nombre' => 'Tasco', 'id_departamento' => 6],
            ['nombre' => 'Tenza', 'id_departamento' => 6],
            ['nombre' => 'Tibaná', 'id_departamento' => 6],
            ['nombre' => 'Tibasosa', 'id_departamento' => 6],
            ['nombre' => 'Tinjacá', 'id_departamento' => 6],
            ['nombre' => 'Tipacoque', 'id_departamento' => 6],
            ['nombre' => 'Toca', 'id_departamento' => 6],
            ['nombre' => 'Togüí', 'id_departamento' => 6],
            ['nombre' => 'Tópaga', 'id_departamento' => 6],
            ['nombre' => 'Tota', 'id_departamento' => 6],
            ['nombre' => 'Tunja (Capital)', 'id_departamento' => 6],
            ['nombre' => 'Tununguá', 'id_departamento' => 6],
            ['nombre' => 'Turmequé', 'id_departamento' => 6],
            ['nombre' => 'Tuta', 'id_departamento' => 6],
            ['nombre' => 'Tutazá', 'id_departamento' => 6],
            ['nombre' => 'Umbita', 'id_departamento' => 6],
            ['nombre' => 'Ventaquemada', 'id_departamento' => 6],
            ['nombre' => 'Villa de Leyva', 'id_departamento' => 6],
            ['nombre' => 'Viracachá', 'id_departamento' => 6],
            ['nombre' => 'Zetaquira', 'id_departamento' => 6],

            //caldas
            ['nombre' => 'Aguadas', 'id_departamento' => 7],
            ['nombre' => 'Anserma', 'id_departamento' => 7],
            ['nombre' => 'Aranzazu', 'id_departamento' => 7],
            ['nombre' => 'Belalcázar', 'id_departamento' => 7],
            ['nombre' => 'Chinchiná', 'id_departamento' => 7],
            ['nombre' => 'Filadelfia', 'id_departamento' => 7],
            ['nombre' => 'La Dorada', 'id_departamento' => 7],
            ['nombre' => 'La Merced', 'id_departamento' => 7],
            ['nombre' => 'Manizales (Capital)', 'id_departamento' => 7],
            ['nombre' => 'Manzanares', 'id_departamento' => 7],
            ['nombre' => 'Marmato', 'id_departamento' => 7],
            ['nombre' => 'Marquetalia', 'id_departamento' => 7],
            ['nombre' => 'Marulanda', 'id_departamento' => 7],
            ['nombre' => 'Neira', 'id_departamento' => 7],
            ['nombre' => 'Norcasia', 'id_departamento' => 7],
            ['nombre' => 'Pácora', 'id_departamento' => 7],
            ['nombre' => 'Palestina', 'id_departamento' => 7],
            ['nombre' => 'Pensilvania', 'id_departamento' => 7],
            ['nombre' => 'Riosucio', 'id_departamento' => 7],
            ['nombre' => 'Risaralda', 'id_departamento' => 7],
            ['nombre' => 'Salamina', 'id_departamento' => 7],
            ['nombre' => 'Samaná', 'id_departamento' => 7],
            ['nombre' => 'San José', 'id_departamento' => 7],
            ['nombre' => 'Supía', 'id_departamento' => 7],
            ['nombre' => 'Victoria', 'id_departamento' => 7],
            ['nombre' => 'Villamaría', 'id_departamento' => 7],
            ['nombre' => 'Viterbo', 'id_departamento' => 7],

            //caquetá
            ['nombre' => 'Albania', 'id_departamento' => 8],
            ['nombre' => 'Belén de Los Andaquies', 'id_departamento' => 8],
            ['nombre' => 'Cartagena del Chairá', 'id_departamento' => 8],
            ['nombre' => 'Curillo', 'id_departamento' => 8],
            ['nombre' => 'El Doncello', 'id_departamento' => 8],
            ['nombre' => 'El Paujil', 'id_departamento' => 8],
            ['nombre' => 'Florencia (Capital)', 'id_departamento' => 8],
            ['nombre' => 'La Montañita', 'id_departamento' => 8],
            ['nombre' => 'Milán', 'id_departamento' => 8],
            ['nombre' => 'Morelia', 'id_departamento' => 8],
            ['nombre' => 'Puerto Rico', 'id_departamento' => 8],
            ['nombre' => 'San José del Fragua', 'id_departamento' => 8],
            ['nombre' => 'San Vicente del Caguán', 'id_departamento' => 8],
            ['nombre' => 'Solano', 'id_departamento' => 8],
            ['nombre' => 'Solita', 'id_departamento' => 8],
            ['nombre' => 'Valparaíso', 'id_departamento' => 8],

            //casanare
            ['nombre' => 'Aguazul', 'id_departamento' => 9],
            ['nombre' => 'Chámeza', 'id_departamento' => 9],
            ['nombre' => 'Hato Corozal', 'id_departamento' => 9],
            ['nombre' => 'La Salina', 'id_departamento' => 9],
            ['nombre' => 'Maní', 'id_departamento' => 9],
            ['nombre' => 'Monterrey', 'id_departamento' => 9],
            ['nombre' => 'Nunchía', 'id_departamento' => 9],
            ['nombre' => 'Orocué', 'id_departamento' => 9],
            ['nombre' => 'Paz de Ariporo', 'id_departamento' => 9],
            ['nombre' => 'Pore', 'id_departamento' => 9],
            ['nombre' => 'Recetor', 'id_departamento' => 9],
            ['nombre' => 'Sabanalarga', 'id_departamento' => 9],
            ['nombre' => 'Sácama', 'id_departamento' => 9],
            ['nombre' => 'San Luis de Gaceno', 'id_departamento' => 9],
            ['nombre' => 'Támara', 'id_departamento' => 9],
            ['nombre' => 'Tauramena', 'id_departamento' => 9],
            ['nombre' => 'Trinidad', 'id_departamento' => 9],
            ['nombre' => 'Villanueva', 'id_departamento' => 9],
            ['nombre' => 'Yopal (Capital)', 'id_departamento' => 9],

            //cauca
            ['nombre' => 'Almaguer', 'id_departamento' => 10],
            ['nombre' => 'Argelia', 'id_departamento' => 10],
            ['nombre' => 'Balboa', 'id_departamento' => 10],
            ['nombre' => 'Cauca', 'id_departamento' => 10],
            ['nombre' => 'Buenos Aires', 'id_departamento' => 10],
            ['nombre' => 'Cajibío', 'id_departamento' => 10],
            ['nombre' => 'Caldono', 'id_departamento' => 10],
            ['nombre' => 'Caloto', 'id_departamento' => 10],
            ['nombre' => 'Corinto', 'id_departamento' => 10],
            ['nombre' => 'El Tambo', 'id_departamento' => 10],
            ['nombre' => 'Florencia', 'id_departamento' => 10],
            ['nombre' => 'Guachené', 'id_departamento' => 10],
            ['nombre' => 'Guapi', 'id_departamento' => 10],
            ['nombre' => 'Inzá', 'id_departamento' => 10],
            ['nombre' => 'Jambaló', 'id_departamento' => 10],
            ['nombre' => 'La Sierra', 'id_departamento' => 10],
            ['nombre' => 'La Vega', 'id_departamento' => 10],
            ['nombre' => 'López', 'id_departamento' => 10],
            ['nombre' => 'Mercaderes', 'id_departamento' => 10],
            ['nombre' => 'Miranda', 'id_departamento' => 10],
            ['nombre' => 'Morales', 'id_departamento' => 10],
            ['nombre' => 'Padilla', 'id_departamento' => 10],
            ['nombre' => 'Páez', 'id_departamento' => 10],
            ['nombre' => 'Patía', 'id_departamento' => 10],
            ['nombre' => 'Piamonte', 'id_departamento' => 10],
            ['nombre' => 'Piendamó', 'id_departamento' => 10],
            ['nombre' => 'Popayán (Capital)', 'id_departamento' => 10],
            ['nombre' => 'Puerto Tejada', 'id_departamento' => 10],
            ['nombre' => 'Puracé', 'id_departamento' => 10],
            ['nombre' => 'Rosas', 'id_departamento' => 10],
            ['nombre' => 'San Sebastián', 'id_departamento' => 10],
            ['nombre' => 'Santa Rosa', 'id_departamento' => 10],
            ['nombre' => 'Santander de Quilichao', 'id_departamento' => 10],
            ['nombre' => 'Silvia', 'id_departamento' => 10],
            ['nombre' => 'Sotara', 'id_departamento' => 10],
            ['nombre' => 'Suárez', 'id_departamento' => 10],
            ['nombre' => 'Sucre', 'id_departamento' => 10],
            ['nombre' => 'Timbío', 'id_departamento' => 10],
            ['nombre' => 'Timbiquí', 'id_departamento' => 10],
            ['nombre' => 'Toribio', 'id_departamento' => 10],
            ['nombre' => 'Totoró', 'id_departamento' => 10],
            ['nombre' => 'Villa Rica', 'id_departamento' => 10],

            //cesar
            ['nombre' => 'Aguachica', 'id_departamento' => 11],
            ['nombre' => 'Agustín Codazzi', 'id_departamento' => 11],
            ['nombre' => 'Astrea', 'id_departamento' => 11],
            ['nombre' => 'Becerril', 'id_departamento' => 11],
            ['nombre' => 'Bosconia', 'id_departamento' => 11],
            ['nombre' => 'Chimichagua', 'id_departamento' => 11],
            ['nombre' => 'Chiriguaná', 'id_departamento' => 11],
            ['nombre' => 'Curumaní', 'id_departamento' => 11],
            ['nombre' => 'El Copey', 'id_departamento' => 11],
            ['nombre' => 'El Paso', 'id_departamento' => 11],
            ['nombre' => 'Gamarra', 'id_departamento' => 11],
            ['nombre' => 'González', 'id_departamento' => 11],
            ['nombre' => 'La Gloria', 'id_departamento' => 11],
            ['nombre' => 'La Jagua de Ibirico', 'id_departamento' => 11],
            ['nombre' => 'La Paz', 'id_departamento' => 11],
            ['nombre' => 'Manaure', 'id_departamento' => 11],
            ['nombre' => 'Pailitas', 'id_departamento' => 11],
            ['nombre' => 'Pelaya', 'id_departamento' => 11],
            ['nombre' => 'Pueblo Bello', 'id_departamento' => 11],
            ['nombre' => 'Río de Oro', 'id_departamento' => 11],
            ['nombre' => 'San Alberto', 'id_departamento' => 11],
            ['nombre' => 'San Diego', 'id_departamento' => 11],
            ['nombre' => 'San Martín', 'id_departamento' => 11],
            ['nombre' => 'Tamalameque', 'id_departamento' => 11],
            ['nombre' => 'Valledupar (Capital)', 'id_departamento' => 11],

            //chochó
            ['nombre' => 'Acandí', 'id_departamento' => 12],
            ['nombre' => 'Alto Baudo', 'id_departamento' => 12],
            ['nombre' => 'Atrato', 'id_departamento' => 12],
            ['nombre' => 'Bagadó', 'id_departamento' => 12],
            ['nombre' => 'Bahía Solano', 'id_departamento' => 12],
            ['nombre' => 'Bajo Baudó', 'id_departamento' => 12],
            ['nombre' => 'Belén de Bajira', 'id_departamento' => 12],
            ['nombre' => 'Bojaya', 'id_departamento' => 12],
            ['nombre' => 'Carmen del Darien', 'id_departamento' => 12],
            ['nombre' => 'Cértegui', 'id_departamento' => 12],
            ['nombre' => 'Condoto', 'id_departamento' => 12],
            ['nombre' => 'El Cantón del San Pablo', 'id_departamento' => 12],
            ['nombre' => 'El Carmen de Atrato', 'id_departamento' => 12],
            ['nombre' => 'El Litoral del San Juan', 'id_departamento' => 12],
            ['nombre' => 'Istmina', 'id_departamento' => 12],
            ['nombre' => 'Juradó', 'id_departamento' => 12],
            ['nombre' => 'Lloró', 'id_departamento' => 12],
            ['nombre' => 'Medio Atrato', 'id_departamento' => 12],
            ['nombre' => 'Medio Baudó', 'id_departamento' => 12],
            ['nombre' => 'Medio San Juan', 'id_departamento' => 12],
            ['nombre' => 'Nóvita', 'id_departamento' => 12],
            ['nombre' => 'Nuquí', 'id_departamento' => 12],
            ['nombre' => 'Quibdó (Capital)', 'id_departamento' => 12],
            ['nombre' => 'Río Iro', 'id_departamento' => 12],
            ['nombre' => 'Río Quito', 'id_departamento' => 12],
            ['nombre' => 'Riosucio', 'id_departamento' => 12],
            ['nombre' => 'San José del Palmar', 'id_departamento' => 12],
            ['nombre' => 'Sipí', 'id_departamento' => 12],
            ['nombre' => 'Tadó', 'id_departamento' => 12],
            ['nombre' => 'Unguía', 'id_departamento' => 12],
            ['nombre' => 'Unión Panamericana', 'id_departamento' => 12],

            //córdoba
            ['nombre' => 'Ayapel', 'id_departamento' => 13],
            ['nombre' => 'Buenavista', 'id_departamento' => 13],
            ['nombre' => 'Canalete', 'id_departamento' => 13],
            ['nombre' => 'Cereté', 'id_departamento' => 13],
            ['nombre' => 'Chimá', 'id_departamento' => 13],
            ['nombre' => 'Chinú', 'id_departamento' => 13],
            ['nombre' => 'Ciénaga de Oro', 'id_departamento' => 13],
            ['nombre' => 'Cotorra', 'id_departamento' => 13],
            ['nombre' => 'La Apartada', 'id_departamento' => 13],
            ['nombre' => 'Lorica', 'id_departamento' => 13],
            ['nombre' => 'Los Córdobas', 'id_departamento' => 13],
            ['nombre' => 'Momil', 'id_departamento' => 13],
            ['nombre' => 'Montelíbano', 'id_departamento' => 13],
            ['nombre' => 'Montería (Capital)', 'id_departamento' => 13],
            ['nombre' => 'Moñitos', 'id_departamento' => 13],
            ['nombre' => 'Planeta Rica', 'id_departamento' => 13],
            ['nombre' => 'Pueblo Nuevo', 'id_departamento' => 13],
            ['nombre' => 'Puerto Escondido', 'id_departamento' => 13],
            ['nombre' => 'Puerto Libertador', 'id_departamento' => 13],
            ['nombre' => 'Purísima', 'id_departamento' => 13],
            ['nombre' => 'Sahagún', 'id_departamento' => 13],
            ['nombre' => 'San Andrés Sotavento', 'id_departamento' => 13],
            ['nombre' => 'San Antero', 'id_departamento' => 13],
            ['nombre' => 'San Bernardo del Viento', 'id_departamento' => 13],
            ['nombre' => 'San Carlos', 'id_departamento' => 13],
            ['nombre' => 'San José de Uré', 'id_departamento' => 13],
            ['nombre' => 'San Pelayo', 'id_departamento' => 13],
            ['nombre' => 'Tierralta', 'id_departamento' => 13],
            ['nombre' => 'Tuchín', 'id_departamento' => 13],
            ['nombre' => 'Valencia', 'id_departamento' => 13],

            //cundinamarca
            ['nombre' => 'Agua de Dios', 'id_departamento' => 14],
            ['nombre' => 'Albán', 'id_departamento' => 14],
            ['nombre' => 'Anapoima', 'id_departamento' => 14],
            ['nombre' => 'Anolaima', 'id_departamento' => 14],
            ['nombre' => 'Apulo', 'id_departamento' => 14],
            ['nombre' => 'Arbeláez', 'id_departamento' => 14],
            ['nombre' => 'Beltrán', 'id_departamento' => 14],
            ['nombre' => 'Bituima', 'id_departamento' => 14],
            ['nombre' => 'Bogotá (Capital)', 'id_departamento' => 14],
            ['nombre' => 'Bojacá', 'id_departamento' => 14],
            ['nombre' => 'Cabrera', 'id_departamento' => 14],
            ['nombre' => 'Cachipay', 'id_departamento' => 14],
            ['nombre' => 'Cajicá', 'id_departamento' => 14],
            ['nombre' => 'Caparrapí', 'id_departamento' => 14],
            ['nombre' => 'Caqueza', 'id_departamento' => 14],
            ['nombre' => 'Carmen de Carupa', 'id_departamento' => 14],
            ['nombre' => 'Chaguaní', 'id_departamento' => 14],
            ['nombre' => 'Chía', 'id_departamento' => 14],
            ['nombre' => 'Chipaque', 'id_departamento' => 14],
            ['nombre' => 'Choachí', 'id_departamento' => 14],
            ['nombre' => 'Chocontá', 'id_departamento' => 14],
            ['nombre' => 'Cogua', 'id_departamento' => 14],
            ['nombre' => 'Cota', 'id_departamento' => 14],
            ['nombre' => 'Cucunubá', 'id_departamento' => 14],
            ['nombre' => 'El Colegio', 'id_departamento' => 14],
            ['nombre' => 'El Peñón', 'id_departamento' => 14],
            ['nombre' => 'El Rosal', 'id_departamento' => 14],
            ['nombre' => 'Facatativá', 'id_departamento' => 14],
            ['nombre' => 'Fomeque', 'id_departamento' => 14],
            ['nombre' => 'Fosca', 'id_departamento' => 14],
            ['nombre' => 'Funza', 'id_departamento' => 14],
            ['nombre' => 'Fúquene', 'id_departamento' => 14],
            ['nombre' => 'Fusagasugá', 'id_departamento' => 14],
            ['nombre' => 'Gachala', 'id_departamento' => 14],
            ['nombre' => 'Gachancipá', 'id_departamento' => 14],
            ['nombre' => 'Gachetá', 'id_departamento' => 14],
            ['nombre' => 'Gama', 'id_departamento' => 14],
            ['nombre' => 'Girardot', 'id_departamento' => 14],
            ['nombre' => 'Granada', 'id_departamento' => 14],
            ['nombre' => 'Guachetá', 'id_departamento' => 14],
            ['nombre' => 'Guaduas', 'id_departamento' => 14],
            ['nombre' => 'Guasca', 'id_departamento' => 14],
            ['nombre' => 'Guataquí', 'id_departamento' => 14],
            ['nombre' => 'Guatavita', 'id_departamento' => 14],
            ['nombre' => 'Guayabal de Siquima', 'id_departamento' => 14],
            ['nombre' => 'Guayabetal', 'id_departamento' => 14],
            ['nombre' => 'Gutiérrez', 'id_departamento' => 14],
            ['nombre' => 'Jerusalén', 'id_departamento' => 14],
            ['nombre' => 'Junín', 'id_departamento' => 14],
            ['nombre' => 'La Calera', 'id_departamento' => 14],
            ['nombre' => 'La Mesa', 'id_departamento' => 14],
            ['nombre' => 'La Palma', 'id_departamento' => 14],
            ['nombre' => 'La Peña', 'id_departamento' => 14],
            ['nombre' => 'La Vega', 'id_departamento' => 14],
            ['nombre' => 'Lenguazaque', 'id_departamento' => 14],
            ['nombre' => 'Macheta', 'id_departamento' => 14],
            ['nombre' => 'Madrid', 'id_departamento' => 14],
            ['nombre' => 'Manta', 'id_departamento' => 14],
            ['nombre' => 'Medina', 'id_departamento' => 14],
            ['nombre' => 'Mosquera', 'id_departamento' => 14],
            ['nombre' => 'Nariño', 'id_departamento' => 14],
            ['nombre' => 'Nemocón', 'id_departamento' => 14],
            ['nombre' => 'Nilo', 'id_departamento' => 14],
            ['nombre' => 'Nimaima', 'id_departamento' => 14],
            ['nombre' => 'Nocaima', 'id_departamento' => 14],
            ['nombre' => 'Pacho', 'id_departamento' => 14],
            ['nombre' => 'Paime', 'id_departamento' => 14],
            ['nombre' => 'Pandi', 'id_departamento' => 14],
            ['nombre' => 'Paratebueno', 'id_departamento' => 14],
            ['nombre' => 'Pasca', 'id_departamento' => 14],
            ['nombre' => 'Puerto Salgar', 'id_departamento' => 14],
            ['nombre' => 'Pulí', 'id_departamento' => 14],
            ['nombre' => 'Quebradanegra', 'id_departamento' => 14],
            ['nombre' => 'Quetame', 'id_departamento' => 14],
            ['nombre' => 'Quipile', 'id_departamento' => 14],
            ['nombre' => 'Ricaurte', 'id_departamento' => 14],
            ['nombre' => 'San Antonio del Tequendama', 'id_departamento' => 14],
            ['nombre' => 'San Bernardo', 'id_departamento' => 14],
            ['nombre' => 'San Cayetano', 'id_departamento' => 14],
            ['nombre' => 'San Francisco', 'id_departamento' => 14],
            ['nombre' => 'San Juan de Río Seco', 'id_departamento' => 14],
            ['nombre' => 'Sasaima', 'id_departamento' => 14],
            ['nombre' => 'Sesquilé', 'id_departamento' => 14],
            ['nombre' => 'Sibaté', 'id_departamento' => 14],
            ['nombre' => 'Silvania', 'id_departamento' => 14],
            ['nombre' => 'Simijaca', 'id_departamento' => 14],
            ['nombre' => 'Soacha', 'id_departamento' => 14],
            ['nombre' => 'Sopó', 'id_departamento' => 14],
            ['nombre' => 'Subachoque', 'id_departamento' => 14],
            ['nombre' => 'Suesca', 'id_departamento' => 14],
            ['nombre' => 'Supatá', 'id_departamento' => 14],
            ['nombre' => 'Susa', 'id_departamento' => 14],
            ['nombre' => 'Sutatausa', 'id_departamento' => 14],
            ['nombre' => 'Tabio', 'id_departamento' => 14],
            ['nombre' => 'Tausa', 'id_departamento' => 14],
            ['nombre' => 'Tena', 'id_departamento' => 14],
            ['nombre' => 'Tenjo', 'id_departamento' => 14],
            ['nombre' => 'Tibacuy', 'id_departamento' => 14],
            ['nombre' => 'Tibirita', 'id_departamento' => 14],
            ['nombre' => 'Tocaima', 'id_departamento' => 14],
            ['nombre' => 'Tocancipá', 'id_departamento' => 14],
            ['nombre' => 'Topaipí', 'id_departamento' => 14],
            ['nombre' => 'Ubalá', 'id_departamento' => 14],
            ['nombre' => 'Ubaque', 'id_departamento' => 14],
            ['nombre' => 'Une', 'id_departamento' => 14],
            ['nombre' => 'Útica', 'id_departamento' => 14],
            ['nombre' => 'Venecia', 'id_departamento' => 14],
            ['nombre' => 'Vergara', 'id_departamento' => 14],
            ['nombre' => 'Vianí', 'id_departamento' => 14],
            ['nombre' => 'Villa de San Diego de Ubate', 'id_departamento' => 14],
            ['nombre' => 'Villagómez', 'id_departamento' => 14],
            ['nombre' => 'Villapinzón', 'id_departamento' => 14],
            ['nombre' => 'Villeta', 'id_departamento' => 14],
            ['nombre' => 'Viotá', 'id_departamento' => 14],
            ['nombre' => 'Yacopí', 'id_departamento' => 14],
            ['nombre' => 'Zipacón', 'id_departamento' => 14],
            ['nombre' => 'Zipaquirá', 'id_departamento' => 14],

            //guainía
            ['nombre' => 'Barranco Minas', 'id_departamento' => 15],
            ['nombre' => 'Cacahual', 'id_departamento' => 15],
            ['nombre' => 'Inírida (Capital)', 'id_departamento' => 15],
            ['nombre' => 'La Guadalupe', 'id_departamento' => 15],
            ['nombre' => 'Mapiripana', 'id_departamento' => 15],
            ['nombre' => 'Morichal', 'id_departamento' => 15],
            ['nombre' => 'Pana Pana', 'id_departamento' => 15],
            ['nombre' => 'Puerto Colombia', 'id_departamento' => 15],
            ['nombre' => 'San Felipe', 'id_departamento' => 15],

            //guaviare
            ['nombre' => 'Calamar', 'id_departamento' => 16],
            ['nombre' => 'El Retorno', 'id_departamento' => 16],
            ['nombre' => 'Miraflores', 'id_departamento' => 16],
            ['nombre' => 'San José del Guaviare (Capital)', 'id_departamento' => 16],

            //huila
            ['nombre' => 'Acevedo', 'id_departamento' => 17],
            ['nombre' => 'Agrado', 'id_departamento' => 17],
            ['nombre' => 'Aipe', 'id_departamento' => 17],
            ['nombre' => 'Algeciras', 'id_departamento' => 17],
            ['nombre' => 'Altamira', 'id_departamento' => 17],
            ['nombre' => 'Baraya', 'id_departamento' => 17],
            ['nombre' => 'Campoalegre', 'id_departamento' => 17],
            ['nombre' => 'Colombia', 'id_departamento' => 17],
            ['nombre' => 'Elías', 'id_departamento' => 17],
            ['nombre' => 'Garzón', 'id_departamento' => 17],
            ['nombre' => 'Gigante', 'id_departamento' => 17],
            ['nombre' => 'Guadalupe', 'id_departamento' => 17],
            ['nombre' => 'Hobo', 'id_departamento' => 17],
            ['nombre' => 'Iquira', 'id_departamento' => 17],
            ['nombre' => 'Isnos', 'id_departamento' => 17],
            ['nombre' => 'La Argentina', 'id_departamento' => 17],
            ['nombre' => 'La Plata', 'id_departamento' => 17],
            ['nombre' => 'Nátaga', 'id_departamento' => 17],
            ['nombre' => 'Neiva (Capital)', 'id_departamento' => 17],
            ['nombre' => 'Oporapa', 'id_departamento' => 17],
            ['nombre' => 'Paicol', 'id_departamento' => 17],
            ['nombre' => 'Palermo', 'id_departamento' => 17],
            ['nombre' => 'Palestina', 'id_departamento' => 17],
            ['nombre' => 'Pital', 'id_departamento' => 17],
            ['nombre' => 'Pitalito', 'id_departamento' => 17],
            ['nombre' => 'Rivera', 'id_departamento' => 17],
            ['nombre' => 'Saladoblanco', 'id_departamento' => 17],
            ['nombre' => 'San Agustín', 'id_departamento' => 17],
            ['nombre' => 'Santa María', 'id_departamento' => 17],
            ['nombre' => 'Suaza', 'id_departamento' => 17],
            ['nombre' => 'Tarqui', 'id_departamento' => 17],
            ['nombre' => 'Tello', 'id_departamento' => 17],
            ['nombre' => 'Teruel', 'id_departamento' => 17],
            ['nombre' => 'Tesalia', 'id_departamento' => 17],
            ['nombre' => 'Timaná', 'id_departamento' => 17],
            ['nombre' => 'Villavieja', 'id_departamento' => 17],
            ['nombre' => 'Yaguará', 'id_departamento' => 17],

            //la guajira
            ['nombre' => 'Albania', 'id_departamento' => 18],
            ['nombre' => 'Barrancas', 'id_departamento' => 18],
            ['nombre' => 'Dibula', 'id_departamento' => 18],
            ['nombre' => 'Distracción', 'id_departamento' => 18],
            ['nombre' => 'El Molino', 'id_departamento' => 18],
            ['nombre' => 'Fonseca', 'id_departamento' => 18],
            ['nombre' => 'Hatonuevo', 'id_departamento' => 18],
            ['nombre' => 'La Jagua del Pilar', 'id_departamento' => 18],
            ['nombre' => 'Maicao', 'id_departamento' => 18],
            ['nombre' => 'Manaure', 'id_departamento' => 18],
            ['nombre' => 'Riohacha (Capital)', 'id_departamento' => 18],
            ['nombre' => 'San Juan del Cesar', 'id_departamento' => 18],
            ['nombre' => 'Uribia', 'id_departamento' => 18],
            ['nombre' => 'Urumita', 'id_departamento' => 18],
            ['nombre' => 'Villanueva', 'id_departamento' => 18],

            //magadalena
            ['nombre' => 'Algarrobo', 'id_departamento' => 19],
            ['nombre' => 'Aracataca', 'id_departamento' => 19],
            ['nombre' => 'Ariguaní', 'id_departamento' => 19],
            ['nombre' => 'Cerro San Antonio', 'id_departamento' => 19],
            ['nombre' => 'Chivolo', 'id_departamento' => 19],
            ['nombre' => 'Ciénaga', 'id_departamento' => 19],
            ['nombre' => 'Concordia', 'id_departamento' => 19],
            ['nombre' => 'El Banco', 'id_departamento' => 19],
            ['nombre' => 'El Piñon', 'id_departamento' => 19],
            ['nombre' => 'El Retén', 'id_departamento' => 19],
            ['nombre' => 'Fundación', 'id_departamento' => 19],
            ['nombre' => 'Guamal', 'id_departamento' => 19],
            ['nombre' => 'Nueva Granada', 'id_departamento' => 19],
            ['nombre' => 'Pedraza', 'id_departamento' => 19],
            ['nombre' => 'Pijiño del Carmen', 'id_departamento' => 19],
            ['nombre' => 'Pivijay', 'id_departamento' => 19],
            ['nombre' => 'Plato', 'id_departamento' => 19],
            ['nombre' => 'Pueblo Viejo', 'id_departamento' => 19],
            ['nombre' => 'Remolino', 'id_departamento' => 19],
            ['nombre' => 'Sabanas de San Angel', 'id_departamento' => 19],
            ['nombre' => 'Salamina', 'id_departamento' => 19],
            ['nombre' => 'San Sebastián de Buenavista', 'id_departamento' => 19],
            ['nombre' => 'San Zenón', 'id_departamento' => 19],
            ['nombre' => 'Santa Ana', 'id_departamento' => 19],
            ['nombre' => 'Santa Bárbara de Pinto', 'id_departamento' => 19],
            ['nombre' => 'Santa Marta (Capital)', 'id_departamento' => 19],
            ['nombre' => 'Sitionuevo', 'id_departamento' => 19],
            ['nombre' => 'Tenerife', 'id_departamento' => 19],
            ['nombre' => 'Zapayán', 'id_departamento' => 19],
            ['nombre' => 'Zona Bananera', 'id_departamento' => 19],

            //meta
            ['nombre' => 'Acacias', 'id_departamento' => 20],
            ['nombre' => 'Barranca de Upía', 'id_departamento' => 20],
            ['nombre' => 'Cabuyaro', 'id_departamento' => 20],
            ['nombre' => 'Castilla la Nueva', 'id_departamento' => 20],
            ['nombre' => 'Cubarral', 'id_departamento' => 20],
            ['nombre' => 'Cumaral', 'id_departamento' => 20],
            ['nombre' => 'El Calvario', 'id_departamento' => 20],
            ['nombre' => 'El Castillo', 'id_departamento' => 20],
            ['nombre' => 'El Dorado', 'id_departamento' => 20],
            ['nombre' => 'Fuente de Oro', 'id_departamento' => 20],
            ['nombre' => 'Granada', 'id_departamento' => 20],
            ['nombre' => 'Guamal', 'id_departamento' => 20],
            ['nombre' => 'La Macarena', 'id_departamento' => 20],
            ['nombre' => 'Lejanías', 'id_departamento' => 20],
            ['nombre' => 'Mapiripán', 'id_departamento' => 20],
            ['nombre' => 'Mesetas', 'id_departamento' => 20],
            ['nombre' => 'Puerto Concordia', 'id_departamento' => 20],
            ['nombre' => 'Puerto Gaitán', 'id_departamento' => 20],
            ['nombre' => 'Puerto Lleras', 'id_departamento' => 20],
            ['nombre' => 'Puerto López', 'id_departamento' => 20],
            ['nombre' => 'Puerto Rico', 'id_departamento' => 20],
            ['nombre' => 'Restrepo', 'id_departamento' => 20],
            ['nombre' => 'San Carlos de Guaroa', 'id_departamento' => 20],
            ['nombre' => 'San Juan de Arama', 'id_departamento' => 20],
            ['nombre' => 'San Juanito', 'id_departamento' => 20],
            ['nombre' => 'San Martín', 'id_departamento' => 20],
            ['nombre' => 'Uribe', 'id_departamento' => 20],
            ['nombre' => 'Villavicencio (Capital)', 'id_departamento' => 20],
            ['nombre' => 'Vista Hermosa', 'id_departamento' => 20],

            //nariño
            ['nombre' => 'Albán', 'id_departamento' => 21],
            ['nombre' => 'Aldana', 'id_departamento' => 21],
            ['nombre' => 'Ancuyá', 'id_departamento' => 21],
            ['nombre' => 'Arboleda', 'id_departamento' => 21],
            ['nombre' => 'Barbacoas', 'id_departamento' => 21],
            ['nombre' => 'Belén', 'id_departamento' => 21],
            ['nombre' => 'Buesaco', 'id_departamento' => 21],
            ['nombre' => 'Chachagüí', 'id_departamento' => 21],
            ['nombre' => 'Colón', 'id_departamento' => 21],
            ['nombre' => 'Consaca', 'id_departamento' => 21],
            ['nombre' => 'Contadero', 'id_departamento' => 21],
            ['nombre' => 'Córdoba', 'id_departamento' => 21],
            ['nombre' => 'Cuaspud', 'id_departamento' => 21],
            ['nombre' => 'Cumbal', 'id_departamento' => 21],
            ['nombre' => 'Cumbitara', 'id_departamento' => 21],
            ['nombre' => 'El Charco', 'id_departamento' => 21],
            ['nombre' => 'El Peñol', 'id_departamento' => 21],
            ['nombre' => 'El Rosario', 'id_departamento' => 21],
            ['nombre' => 'El Tablón de Gómez', 'id_departamento' => 21],
            ['nombre' => 'El Tambo', 'id_departamento' => 21],
            ['nombre' => 'Francisco Pizarro', 'id_departamento' => 21],
            ['nombre' => 'Funes', 'id_departamento' => 21],
            ['nombre' => 'Guachucal', 'id_departamento' => 21],
            ['nombre' => 'Guaitarilla', 'id_departamento' => 21],
            ['nombre' => 'Gualmatán', 'id_departamento' => 21],
            ['nombre' => 'Iles', 'id_departamento' => 21],
            ['nombre' => 'Imués', 'id_departamento' => 21],
            ['nombre' => 'Ipiales', 'id_departamento' => 21],
            ['nombre' => 'La Cruz', 'id_departamento' => 21],
            ['nombre' => 'La Florida', 'id_departamento' => 21],
            ['nombre' => 'La Llanada', 'id_departamento' => 21],
            ['nombre' => 'La Tola', 'id_departamento' => 21],
            ['nombre' => 'La Unión', 'id_departamento' => 21],
            ['nombre' => 'Leiva', 'id_departamento' => 21],
            ['nombre' => 'Linares', 'id_departamento' => 21],
            ['nombre' => 'Los Andes', 'id_departamento' => 21],
            ['nombre' => 'Magüí', 'id_departamento' => 21],
            ['nombre' => 'Mallama', 'id_departamento' => 21],
            ['nombre' => 'Mosquera', 'id_departamento' => 21],
            ['nombre' => 'Nariño', 'id_departamento' => 21],
            ['nombre' => 'Olaya Herrera', 'id_departamento' => 21],
            ['nombre' => 'Ospina', 'id_departamento' => 21],
            ['nombre' => 'Pasto (Capital)', 'id_departamento' => 21],
            ['nombre' => 'Policarpa', 'id_departamento' => 21],
            ['nombre' => 'Potosí', 'id_departamento' => 21],
            ['nombre' => 'Providencia', 'id_departamento' => 21],
            ['nombre' => 'Puerres', 'id_departamento' => 21],
            ['nombre' => 'Pupiales', 'id_departamento' => 21],
            ['nombre' => 'Ricaurte', 'id_departamento' => 21],
            ['nombre' => 'Roberto Payán', 'id_departamento' => 21],
            ['nombre' => 'Samaniego', 'id_departamento' => 21],
            ['nombre' => 'San Andrés de Tumaco', 'id_departamento' => 21],
            ['nombre' => 'San Bernardo', 'id_departamento' => 21],
            ['nombre' => 'San Lorenzo', 'id_departamento' => 21],
            ['nombre' => 'San Pablo', 'id_departamento' => 21],
            ['nombre' => 'San Pedro de Cartago', 'id_departamento' => 21],
            ['nombre' => 'Sandoná', 'id_departamento' => 21],
            ['nombre' => 'Santa Bárbara', 'id_departamento' => 21],
            ['nombre' => 'Santacruz', 'id_departamento' => 21],
            ['nombre' => 'Sapuyes', 'id_departamento' => 21],
            ['nombre' => 'Taminango', 'id_departamento' => 21],
            ['nombre' => 'Tangua', 'id_departamento' => 21],
            ['nombre' => 'Túquerres', 'id_departamento' => 21],
            ['nombre' => 'Yacuanquer', 'id_departamento' => 21],

            //norte de santander
            ['nombre' => 'Abrego', 'id_departamento' => 22],
            ['nombre' => 'Arboledas', 'id_departamento' => 22],
            ['nombre' => 'Bochalema', 'id_departamento' => 22],
            ['nombre' => 'Bucarasica', 'id_departamento' => 22],
            ['nombre' => 'Cachirá', 'id_departamento' => 22],
            ['nombre' => 'Cácota', 'id_departamento' => 22],
            ['nombre' => 'Chinácota', 'id_departamento' => 22],
            ['nombre' => 'Chitagá', 'id_departamento' => 22],
            ['nombre' => 'Convención', 'id_departamento' => 22],
            ['nombre' => 'Cúcuta (Capital)', 'id_departamento' => 22],
            ['nombre' => 'Cucutilla', 'id_departamento' => 22],
            ['nombre' => 'Durania', 'id_departamento' => 22],
            ['nombre' => 'El Carmen', 'id_departamento' => 22],
            ['nombre' => 'El Tarra', 'id_departamento' => 22],
            ['nombre' => 'El Zulia', 'id_departamento' => 22],
            ['nombre' => 'Gramalote', 'id_departamento' => 22],
            ['nombre' => 'Hacarí', 'id_departamento' => 22],
            ['nombre' => 'Herrán', 'id_departamento' => 22],
            ['nombre' => 'La Esperanza', 'id_departamento' => 22],
            ['nombre' => 'La Playa', 'id_departamento' => 22],
            ['nombre' => 'Labateca', 'id_departamento' => 22],
            ['nombre' => 'Los Patios', 'id_departamento' => 22],
            ['nombre' => 'Lourdes', 'id_departamento' => 22],
            ['nombre' => 'Mutiscua', 'id_departamento' => 22],
            ['nombre' => 'Ocaña', 'id_departamento' => 22],
            ['nombre' => 'Pamplona', 'id_departamento' => 22],
            ['nombre' => 'Pamplonita', 'id_departamento' => 22],
            ['nombre' => 'Puerto Santander', 'id_departamento' => 22],
            ['nombre' => 'Ragonvalia', 'id_departamento' => 22],
            ['nombre' => 'Salazar', 'id_departamento' => 22],
            ['nombre' => 'San Calixto', 'id_departamento' => 22],
            ['nombre' => 'San Cayetano', 'id_departamento' => 22],
            ['nombre' => 'Santiago', 'id_departamento' => 22],
            ['nombre' => 'Sardinata', 'id_departamento' => 22],
            ['nombre' => 'Silos', 'id_departamento' => 22],
            ['nombre' => 'Teorama', 'id_departamento' => 22],
            ['nombre' => 'Tibú', 'id_departamento' => 22],
            ['nombre' => 'Toledo', 'id_departamento' => 22],
            ['nombre' => 'Villa Caro', 'id_departamento' => 22],
            ['nombre' => 'Villa del Rosario', 'id_departamento' => 22],

            //putumayo
            ['nombre' => 'Colón', 'id_departamento' => 23],
            ['nombre' => 'Leguízamo', 'id_departamento' => 23],
            ['nombre' => 'Mocoa (Capital)', 'id_departamento' => 23],
            ['nombre' => 'Orito', 'id_departamento' => 23],
            ['nombre' => 'Puerto Asís', 'id_departamento' => 23],
            ['nombre' => 'Puerto Caicedo', 'id_departamento' => 23],
            ['nombre' => 'Puerto Guzmán', 'id_departamento' => 23],
            ['nombre' => 'San Francisco', 'id_departamento' => 23],
            ['nombre' => 'San Miguel', 'id_departamento' => 23],
            ['nombre' => 'Santiago', 'id_departamento' => 23],
            ['nombre' => 'Sibundoy', 'id_departamento' => 23],
            ['nombre' => 'Valle de Guamez', 'id_departamento' => 23],
            ['nombre' => 'Villagarzón', 'id_departamento' => 23],

            //quindío
            ['nombre' => 'Armenia (Capital)', 'id_departamento' => 24],
            ['nombre' => 'Buenavista', 'id_departamento' => 24],
            ['nombre' => 'Calarcá', 'id_departamento' => 24],
            ['nombre' => 'Circasia', 'id_departamento' => 24],
            ['nombre' => 'Córdoba', 'id_departamento' => 24],
            ['nombre' => 'Filandia', 'id_departamento' => 24],
            ['nombre' => 'Génova', 'id_departamento' => 24],
            ['nombre' => 'La Tebaida', 'id_departamento' => 24],
            ['nombre' => 'Montenegro', 'id_departamento' => 24],
            ['nombre' => 'Pijao', 'id_departamento' => 24],
            ['nombre' => 'Quimbaya', 'id_departamento' => 24],
            ['nombre' => 'Salento', 'id_departamento' => 24],

            //risaralda
            ['nombre' => 'Apía', 'id_departamento' => 25],
            ['nombre' => 'Balboa', 'id_departamento' => 25],
            ['nombre' => 'Belén de Umbría', 'id_departamento' => 25],
            ['nombre' => 'Dosquebradas', 'id_departamento' => 25],
            ['nombre' => 'Guática', 'id_departamento' => 25],
            ['nombre' => 'La Celia', 'id_departamento' => 25],
            ['nombre' => 'La Virginia', 'id_departamento' => 25],
            ['nombre' => 'Marsella', 'id_departamento' => 25],
            ['nombre' => 'Mistrató', 'id_departamento' => 25],
            ['nombre' => 'Pereira (Capital)', 'id_departamento' => 25],
            ['nombre' => 'Pueblo Rico', 'id_departamento' => 25],
            ['nombre' => 'Quinchía', 'id_departamento' => 25],
            ['nombre' => 'Santa Rosa de Cabal', 'id_departamento' => 25],
            ['nombre' => 'Santuario', 'id_departamento' => 25],

            //san andrés y providencia
            ['nombre' => 'Providencia', 'id_departamento' => 26],
            ['nombre' => 'San Andrés (Capital)', 'id_departamento' => 26],

            //santander
            ['nombre' => 'Aguada', 'id_departamento' => 27],
            ['nombre' => 'Albania', 'id_departamento' => 27],
            ['nombre' => 'Aratoca', 'id_departamento' => 27],
            ['nombre' => 'Barbosa', 'id_departamento' => 27],
            ['nombre' => 'Barichara', 'id_departamento' => 27],
            ['nombre' => 'Barrancabermeja', 'id_departamento' => 27],
            ['nombre' => 'Betulia', 'id_departamento' => 27],
            ['nombre' => 'Bolívar', 'id_departamento' => 27],
            ['nombre' => 'Bucaramanga (Capital)', 'id_departamento' => 27],
            ['nombre' => 'Cabrera', 'id_departamento' => 27],
            ['nombre' => 'California', 'id_departamento' => 27],
            ['nombre' => 'Capitanejo', 'id_departamento' => 27],
            ['nombre' => 'Carcasí', 'id_departamento' => 27],
            ['nombre' => 'Cepitá', 'id_departamento' => 27],
            ['nombre' => 'Cerrito', 'id_departamento' => 27],
            ['nombre' => 'Charalá', 'id_departamento' => 27],
            ['nombre' => 'Charta', 'id_departamento' => 27],
            ['nombre' => 'Chimá', 'id_departamento' => 27],
            ['nombre' => 'Chipatá', 'id_departamento' => 27],
            ['nombre' => 'Cimitarra', 'id_departamento' => 27],
            ['nombre' => 'Concepción', 'id_departamento' => 27],
            ['nombre' => 'Confines', 'id_departamento' => 27],
            ['nombre' => 'Contratación', 'id_departamento' => 27],
            ['nombre' => 'Coromoro', 'id_departamento' => 27],
            ['nombre' => 'Curití', 'id_departamento' => 27],
            ['nombre' => 'El Carmen de Chucurí', 'id_departamento' => 27],
            ['nombre' => 'El Guacamayo', 'id_departamento' => 27],
            ['nombre' => 'El Peñón', 'id_departamento' => 27],
            ['nombre' => 'El Playón', 'id_departamento' => 27],
            ['nombre' => 'Encino', 'id_departamento' => 27],
            ['nombre' => 'Enciso', 'id_departamento' => 27],
            ['nombre' => 'Florián', 'id_departamento' => 27],
            ['nombre' => 'Floridablanca', 'id_departamento' => 27],
            ['nombre' => 'Galán', 'id_departamento' => 27],
            ['nombre' => 'Gambita', 'id_departamento' => 27],
            ['nombre' => 'Girón', 'id_departamento' => 27],
            ['nombre' => 'Guaca', 'id_departamento' => 27],
            ['nombre' => 'Guadalupe', 'id_departamento' => 27],
            ['nombre' => 'Guapotá', 'id_departamento' => 27],
            ['nombre' => 'Guavatá', 'id_departamento' => 27],
            ['nombre' => 'Güepsa', 'id_departamento' => 27],
            ['nombre' => 'Hato', 'id_departamento' => 27],
            ['nombre' => 'Jesús María', 'id_departamento' => 27],
            ['nombre' => 'Jordán', 'id_departamento' => 27],
            ['nombre' => 'La Belleza', 'id_departamento' => 27],
            ['nombre' => 'La Paz', 'id_departamento' => 27],
            ['nombre' => 'Landázuri', 'id_departamento' => 27],
            ['nombre' => 'Lebríja', 'id_departamento' => 27],
            ['nombre' => 'Los Santos', 'id_departamento' => 27],
            ['nombre' => 'Macaravita', 'id_departamento' => 27],
            ['nombre' => 'Málaga', 'id_departamento' => 27],
            ['nombre' => 'Matanza', 'id_departamento' => 27],
            ['nombre' => 'Mogotes', 'id_departamento' => 27],
            ['nombre' => 'Molagavita', 'id_departamento' => 27],
            ['nombre' => 'Ocamonte', 'id_departamento' => 27],
            ['nombre' => 'Oiba', 'id_departamento' => 27],
            ['nombre' => 'Onzaga', 'id_departamento' => 27],
            ['nombre' => 'Palmar', 'id_departamento' => 27],
            ['nombre' => 'Palmas del Socorro', 'id_departamento' => 27],
            ['nombre' => 'Páramo', 'id_departamento' => 27],
            ['nombre' => 'Piedecuesta', 'id_departamento' => 27],
            ['nombre' => 'Pinchote', 'id_departamento' => 27],
            ['nombre' => 'Puente Nacional', 'id_departamento' => 27],
            ['nombre' => 'Puerto Parra', 'id_departamento' => 27],
            ['nombre' => 'Puerto Wilches', 'id_departamento' => 27],
            ['nombre' => 'Rionegro', 'id_departamento' => 27],
            ['nombre' => 'Sabana de Torres', 'id_departamento' => 27],
            ['nombre' => 'San Andrés', 'id_departamento' => 27],
            ['nombre' => 'San Benito', 'id_departamento' => 27],
            ['nombre' => 'San Gil', 'id_departamento' => 27],
            ['nombre' => 'San Joaquín', 'id_departamento' => 27],
            ['nombre' => 'San José de Miranda', 'id_departamento' => 27],
            ['nombre' => 'San Miguel', 'id_departamento' => 27],
            ['nombre' => 'San Vicente de Chucurí', 'id_departamento' => 27],
            ['nombre' => 'Santa Bárbara', 'id_departamento' => 27],
            ['nombre' => 'Santa Helena del Opón', 'id_departamento' => 27],
            ['nombre' => 'Simacota', 'id_departamento' => 27],
            ['nombre' => 'Socorro', 'id_departamento' => 27],
            ['nombre' => 'Suaita', 'id_departamento' => 27],
            ['nombre' => 'Sucre', 'id_departamento' => 27],
            ['nombre' => 'Suratá', 'id_departamento' => 27],
            ['nombre' => 'Tona', 'id_departamento' => 27],
            ['nombre' => 'Valle de San José', 'id_departamento' => 27],
            ['nombre' => 'Vélez', 'id_departamento' => 27],
            ['nombre' => 'Vetas', 'id_departamento' => 27],
            ['nombre' => 'Villanueva', 'id_departamento' => 27],
            ['nombre' => 'Zapatoca', 'id_departamento' => 27],

            //sucre
            ['nombre' => 'Buenavista', 'id_departamento' => 28],
            ['nombre' => 'Caimito', 'id_departamento' => 28],
            ['nombre' => 'Chalán', 'id_departamento' => 28],
            ['nombre' => 'Coloso', 'id_departamento' => 28],
            ['nombre' => 'Corozal', 'id_departamento' => 28],
            ['nombre' => 'Coveñas', 'id_departamento' => 28],
            ['nombre' => 'El Roble', 'id_departamento' => 28],
            ['nombre' => 'Galeras', 'id_departamento' => 28],
            ['nombre' => 'Guaranda', 'id_departamento' => 28],
            ['nombre' => 'La Unión', 'id_departamento' => 28],
            ['nombre' => 'Los Palmitos', 'id_departamento' => 28],
            ['nombre' => 'Majagual', 'id_departamento' => 28],
            ['nombre' => 'Morroa', 'id_departamento' => 28],
            ['nombre' => 'Ovejas', 'id_departamento' => 28],
            ['nombre' => 'Palmito', 'id_departamento' => 28],
            ['nombre' => 'Sampués', 'id_departamento' => 28],
            ['nombre' => 'San Benito Abad', 'id_departamento' => 28],
            ['nombre' => 'San Juan de Betulia', 'id_departamento' => 28],
            ['nombre' => 'San Luis de Sincé', 'id_departamento' => 28],
            ['nombre' => 'San Marcos', 'id_departamento' => 28],
            ['nombre' => 'San Onofre', 'id_departamento' => 28],
            ['nombre' => 'San Pedro', 'id_departamento' => 28],
            ['nombre' => 'Santiago de Tolú', 'id_departamento' => 28],
            ['nombre' => 'Sincelejo (Capital)', 'id_departamento' => 28],
            ['nombre' => 'Sucre', 'id_departamento' => 28],
            ['nombre' => 'Tolú Viejo', 'id_departamento' => 28],

            //tolima
            ['nombre' => 'Alpujarra', 'id_departamento' => 29],
            ['nombre' => 'Alvarado', 'id_departamento' => 29],
            ['nombre' => 'Ambalema', 'id_departamento' => 29],
            ['nombre' => 'Anzoátegui', 'id_departamento' => 29],
            ['nombre' => 'Armero', 'id_departamento' => 29],
            ['nombre' => 'Ataco', 'id_departamento' => 29],
            ['nombre' => 'Cajamarca', 'id_departamento' => 29],
            ['nombre' => 'Carmen de Apicala', 'id_departamento' => 29],
            ['nombre' => 'Casabianca', 'id_departamento' => 29],
            ['nombre' => 'Chaparral', 'id_departamento' => 29],
            ['nombre' => 'Coello', 'id_departamento' => 29],
            ['nombre' => 'Coyaima', 'id_departamento' => 29],
            ['nombre' => 'Cunday', 'id_departamento' => 29],
            ['nombre' => 'Dolores', 'id_departamento' => 29],
            ['nombre' => 'Espinal', 'id_departamento' => 29],
            ['nombre' => 'Falan', 'id_departamento' => 29],
            ['nombre' => 'Flandes', 'id_departamento' => 29],
            ['nombre' => 'Fresno', 'id_departamento' => 29],
            ['nombre' => 'Guamo', 'id_departamento' => 29],
            ['nombre' => 'Herveo', 'id_departamento' => 29],
            ['nombre' => 'Honda', 'id_departamento' => 29],
            ['nombre' => 'Ibagué (Capital)', 'id_departamento' => 29],
            ['nombre' => 'Icononzo', 'id_departamento' => 29],
            ['nombre' => 'Lérida', 'id_departamento' => 29],
            ['nombre' => 'Líbano', 'id_departamento' => 29],
            ['nombre' => 'Mariquita', 'id_departamento' => 29],
            ['nombre' => 'Melgar', 'id_departamento' => 29],
            ['nombre' => 'Murillo', 'id_departamento' => 29],
            ['nombre' => 'Natagaima', 'id_departamento' => 29],
            ['nombre' => 'Ortega', 'id_departamento' => 29],
            ['nombre' => 'Palocabildo', 'id_departamento' => 29],
            ['nombre' => 'Piedras', 'id_departamento' => 29],
            ['nombre' => 'Planadas', 'id_departamento' => 29],
            ['nombre' => 'Prado', 'id_departamento' => 29],
            ['nombre' => 'Purificación', 'id_departamento' => 29],
            ['nombre' => 'Rio Blanc', 'id_departamento' => 29],
            ['nombre' => 'Roncesvalles', 'id_departamento' => 29],
            ['nombre' => 'Rovira', 'id_departamento' => 29],
            ['nombre' => 'Saldaña', 'id_departamento' => 29],
            ['nombre' => 'San Antonio', 'id_departamento' => 29],
            ['nombre' => 'San Luis', 'id_departamento' => 29],
            ['nombre' => 'Santa Isabel', 'id_departamento' => 29],
            ['nombre' => 'Suárez', 'id_departamento' => 29],
            ['nombre' => 'Valle de San Juan', 'id_departamento' => 29],
            ['nombre' => 'Venadillo', 'id_departamento' => 29],
            ['nombre' => 'Villahermosa', 'id_departamento' => 29],
            ['nombre' => 'Villarrica', 'id_departamento' => 29],

            //valle del cauca
            ['nombre' => 'Alcalá', 'id_departamento' => 30],
            ['nombre' => 'Andalucía', 'id_departamento' => 30],
            ['nombre' => 'Ansermanuevo', 'id_departamento' => 30],
            ['nombre' => 'Argelia', 'id_departamento' => 30],
            ['nombre' => 'Bolívar', 'id_departamento' => 30],
            ['nombre' => 'Buenaventura', 'id_departamento' => 30],
            ['nombre' => 'Bugalagrande', 'id_departamento' => 30],
            ['nombre' => 'Caicedonia', 'id_departamento' => 30],
            ['nombre' => 'Cali (Capital)', 'id_departamento' => 30],
            ['nombre' => 'Calima', 'id_departamento' => 30],
            ['nombre' => 'Candelaria', 'id_departamento' => 30],
            ['nombre' => 'Cartago', 'id_departamento' => 30],
            ['nombre' => 'Dagua', 'id_departamento' => 30],
            ['nombre' => 'El Águila', 'id_departamento' => 30],
            ['nombre' => 'El Cairo', 'id_departamento' => 30],
            ['nombre' => 'El Cerrito', 'id_departamento' => 30],
            ['nombre' => 'El Dovio', 'id_departamento' => 30],
            ['nombre' => 'Florida', 'id_departamento' => 30],
            ['nombre' => 'Ginebra', 'id_departamento' => 30],
            ['nombre' => 'Guacarí', 'id_departamento' => 30],
            ['nombre' => 'Guadalajara de Buga', 'id_departamento' => 30],
            ['nombre' => 'Jamundí', 'id_departamento' => 30],
            ['nombre' => 'La Cumbre', 'id_departamento' => 30],
            ['nombre' => 'La Unión', 'id_departamento' => 30],
            ['nombre' => 'La Victoria', 'id_departamento' => 30],
            ['nombre' => 'Obando', 'id_departamento' => 30],
            ['nombre' => 'Palmira', 'id_departamento' => 30],
            ['nombre' => 'Pradera', 'id_departamento' => 30],
            ['nombre' => 'Restrepo', 'id_departamento' => 30],
            ['nombre' => 'Riofrío', 'id_departamento' => 30],
            ['nombre' => 'Roldanillo', 'id_departamento' => 30],
            ['nombre' => 'San Pedro', 'id_departamento' => 30],
            ['nombre' => 'Sevilla', 'id_departamento' => 30],
            ['nombre' => 'Toro', 'id_departamento' => 30],
            ['nombre' => 'Trujillo', 'id_departamento' => 30],
            ['nombre' => 'Tuluá', 'id_departamento' => 30],
            ['nombre' => 'Ulloa', 'id_departamento' => 30],
            ['nombre' => 'Versalles', 'id_departamento' => 30],
            ['nombre' => 'Vijes', 'id_departamento' => 30],
            ['nombre' => 'Yotoco', 'id_departamento' => 30],
            ['nombre' => 'Yumbo', 'id_departamento' => 30],
            ['nombre' => 'Zarzal', 'id_departamento' => 30],

            //vaupés
            ['nombre' => 'Caruru', 'id_departamento' => 31],
            ['nombre' => 'Mitú (Capital)', 'id_departamento' => 31],
            ['nombre' => 'Pacoa', 'id_departamento' => 31],
            ['nombre' => 'Papunaua', 'id_departamento' => 31],
            ['nombre' => 'Taraira', 'id_departamento' => 31],
            ['nombre' => 'Yavaraté', 'id_departamento' => 31],

            //vichada
            ['nombre' => 'Cumaribo', 'id_departamento' => 32],
            ['nombre' => 'La Primavera', 'id_departamento' => 32],
            ['nombre' => 'Puerto Carreño (Capital)', 'id_departamento' => 32],
            ['nombre' => 'Santa Rosalía', 'id_departamento' => 32]


        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('municipios');
    }
}
